name: build-env
channels:
  - conda-forge
dependencies:
  # - jupyterlite-pyodide-kernel>=0.5.2
  - jupyterlite-xeus
  - voici_core>=0.9
  - python-libarchive-c # not strictly needed, but silences a build-time warning about missing libarchive-c