name: build-env
channels:
  - conda-forge
dependencies:
  - jupyterlite-xeus>=2.0.0
  - voici_core>=0.7
  - python-libarchive-c # not strictly needed, but silences a build-time warning about missing libarchive-c