name: my-dashboard-env
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - jupyterlite-pyodide-kernel>=0.5.2
  - pip:
    - parliamentarch>=1.1.2
    - ipywidgets>=8.1.7